/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DesignDocsRouteImport } from './routes/design-docs'
import { Route as IndexRouteImport } from './routes/index'

const SignupLazyRouteImport = createFileRoute('/signup')()
const PricingIndexLazyRouteImport = createFileRoute('/pricing/')()
const FeaturesIndexLazyRouteImport = createFileRoute('/features/')()

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const DesignDocsRoute = DesignDocsRouteImport.update({
  id: '/design-docs',
  path: '/design-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexLazyRoute = PricingIndexLazyRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pricing/index.lazy').then((d) => d.Route))
const FeaturesIndexLazyRoute = FeaturesIndexLazyRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/features/index.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-docs': typeof DesignDocsRoute
  '/signup': typeof SignupLazyRoute
  '/features': typeof FeaturesIndexLazyRoute
  '/pricing': typeof PricingIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-docs': typeof DesignDocsRoute
  '/signup': typeof SignupLazyRoute
  '/features': typeof FeaturesIndexLazyRoute
  '/pricing': typeof PricingIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-docs': typeof DesignDocsRoute
  '/signup': typeof SignupLazyRoute
  '/features/': typeof FeaturesIndexLazyRoute
  '/pricing/': typeof PricingIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design-docs' | '/signup' | '/features' | '/pricing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design-docs' | '/signup' | '/features' | '/pricing'
  id: '__root__' | '/' | '/design-docs' | '/signup' | '/features/' | '/pricing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignDocsRoute: typeof DesignDocsRoute
  SignupLazyRoute: typeof SignupLazyRoute
  FeaturesIndexLazyRoute: typeof FeaturesIndexLazyRoute
  PricingIndexLazyRoute: typeof PricingIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-docs': {
      id: '/design-docs'
      path: '/design-docs'
      fullPath: '/design-docs'
      preLoaderRoute: typeof DesignDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignDocsRoute: DesignDocsRoute,
  SignupLazyRoute: SignupLazyRoute,
  FeaturesIndexLazyRoute: FeaturesIndexLazyRoute,
  PricingIndexLazyRoute: PricingIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
